# Generated by Django 4.2.2 on 2023-06-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("example_sites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pythonwebbasicsmodel",
            name="site_url",
            field=models.URLField(default="default"),
            preserve_default=False,
        ),
    ]
