# Generated by Django 4.2.2 on 2023-06-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("example_sites", "0007_suggestions"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordBotsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("image_url", models.URLField()),
                ("site_url", models.URLField()),
                ("code_link", models.URLField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GamesProjectsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("image_url", models.URLField()),
                ("site_url", models.URLField()),
                ("code_link", models.URLField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HTMLCSSModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("image_url", models.URLField()),
                ("site_url", models.URLField()),
                ("code_link", models.URLField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OtherProjectsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("image_url", models.URLField()),
                ("site_url", models.URLField()),
                ("code_link", models.URLField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SuggestionsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("image_url", models.URLField()),
                ("site_url", models.URLField()),
                ("code_link", models.URLField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="DiscordBots",
        ),
        migrations.DeleteModel(
            name="GamesProjects",
        ),
        migrations.DeleteModel(
            name="HTMLCSS",
        ),
        migrations.DeleteModel(
            name="OtherProjects",
        ),
        migrations.DeleteModel(
            name="Suggestions",
        ),
        migrations.AlterField(
            model_name="jsadvancedmodel",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="jsfrontendmodel",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="pythonwebbasicsmodel",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
