# Generated by Django 4.2.2 on 2023-06-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "example_sites",
            "0008_discordbotsmodel_gamesprojectsmodel_htmlcssmodel_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BooksModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("image_url", models.URLField()),
                ("site_url", models.URLField()),
                ("code_link", models.URLField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WebSitesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("image_url", models.URLField()),
                ("site_url", models.URLField()),
                ("code_link", models.URLField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
