# Generated by Django 4.2.2 on 2023-06-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiscordBotFeaturesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("command", models.CharField(max_length=10)),
                ("image_url", models.URLField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
