# Generated by Django 4.2.2 on 2023-06-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discord_bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discordbotfeaturesmodel",
            name="description",
            field=models.CharField(default="default", max_length=500),
            preserve_default=False,
        ),
    ]
